version: "3.8"

services:
    data:
        container_name: sqlserver
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
            - "1433:1433"
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=yourStrongPassword12!@
        volumes:
            - sqldata:/var/opt/mssql
        networks:
            - casino-network
    messages:
        container_name: rabbitmq
        image: rabbitmq:3-management
        ports:
            - "15672:15672"
            - "5672:5672"
        hostname: "rabbitmq"
        environment:
            - RABBITMQ_ERLANG_COOKIE=Rand0mR4bbitMqCo0k1e
            - RABBITMQ_DEFAULT_USER=rabbitmq
            - RABBITMQ_DEFAULT_PASS=rabbitmq
        networks:
            - casino-network
    identity:
        container_name: identity
        build:
            context: ./
            dockerfile: ./Casino.Identity/Dockerfile
        ports:
            - "5001:80"
        environment:
            - ApplicationSettings__Secret=R4ND0MLY G3N3R473D US3R S3CR37
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=CasinoIdentityDatabase;User Id=sa; Password=yourStrongPassword12!@;MultipleActiveResultSets=true
        restart: on-failure
        volumes:
            - ./.aspnet/identity/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
        networks:
            - casino-network
        depends_on:
            - data
    slot:
        container_name: slot
        build:
            context: ./
            dockerfile: ./Casino.Slot/Dockerfile
        ports:
            - "6001:80"
        environment:
            - ApplicationSettings__Secret=R4ND0MLY G3N3R473D US3R S3CR37
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=CasinoSlotDatabase;User Id=sa; Password=yourStrongPassword12!@;MultipleActiveResultSets=true
        restart: on-failure
        volumes:
            - ./.aspnet/slot/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
        networks:
            - casino-network
        depends_on:
            - data
            - messages
    history:
        container_name: history
        build:
            context: ./
            dockerfile: ./Casino.UserHistory/Dockerfile
        ports:
            - "7001:80"
        environment:
            - ApplicationSettings__Secret=R4ND0MLY G3N3R473D US3R S3CR37
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=CasinoUserHistoryDatabase;User Id=sa; Password=yourStrongPassword12!@;MultipleActiveResultSets=true
        restart: on-failure
        volumes:
            - ./.aspnet/history/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
        networks:
            - casino-network
        depends_on:
            - data
            - messages
    client:
        container_name: client
        build:
            context: ./
            dockerfile: ./Casino/Dockerfile
        ports:
            - "4001:80"
        environment:
            - ApplicationSettings__Secret=R4ND0MLY G3N3R473D US3R S3CR37
            - ServiceEndpoints__Identity=http://identity
            - ServiceEndpoints__Slot=http://slot
            - ServiceEndpoints__UserHistory=http://history
        restart: on-failure
        volumes:
            -   ./.aspnet/client/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
        networks:
            - casino-network
        depends_on:
            - identity
            - history
            - slot               
networks:
    casino-network:
volumes:
    sqldata: